In [4]:
from scipy.stats import f_oneway, norm
import numpy as np

In [21]:
pop = norm.rvs(loc=np.array([[10,20,30,40,50]]), scale=4,size=(10,5)).T

In [10]:
list(pop)

[array([ 4.97045987, 24.30737686, 30.56213819, 35.44482802, 53.58071245]),
 array([ 5.59727084, 24.37463996, 27.8372555 , 38.71456609, 47.5223935 ]),
 array([12.36784804, 19.70651761, 27.50321387, 33.30477492, 47.92118057]),
 array([ 5.36784487, 23.04075182, 30.87998347, 40.01209432, 52.27714574]),
 array([19.26159641, 18.02142983, 24.4460675 , 43.44600062, 50.47523277]),
 array([12.27274695, 21.35110518, 26.19219284, 34.90730508, 47.35440018]),
 array([10.8889052 , 19.64523223, 32.5983322 , 40.08534694, 49.00279112]),
 array([13.86839823, 24.12446078, 24.36173535, 33.71867365, 52.37176447]),
 array([16.1689341 , 17.06283729, 29.79707462, 38.27713198, 48.61346183]),
 array([ 2.04975028, 13.9405593 , 33.83930173, 43.92472513, 52.52952149])]

In [29]:
f_oneway(*pop)

F_onewayResult(statistic=133.16346285125456, pvalue=2.4955292429968356e-24)

In [22]:
f_oneway(pop[0],pop[1],pop[2])

F_onewayResult(statistic=65.82885870595447, pvalue=4.141756772673157e-11)

In [28]:
f_oneway(norm.rvs(loc=10, scale=4,size=10),norm.rvs(loc=15, scale=3,size=13),norm.rvs(loc=1, scale=3,size=5))

F_onewayResult(statistic=26.8431284654707, pvalue=5.96367579492777e-07)